// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/submit-demo-request.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var submit_demo_request_default = defineTool({
  name: "submit_demo_request",
  title: "Submit demo request",
  description: "Submit a demo / contact request to KredibilityPay's sales team on behalf of the signed-in user. Also saves the request to the user's history.",
  inputSchema: {
    name: z.string().min(1).describe("Full name of the contact."),
    email: z.string().email().describe("Business email of the contact."),
    company: z.string().optional().describe("Company name."),
    message: z.string().min(1).describe("What they want to solve, markets, expected volume, etc."),
    monthly_volume: z.string().optional().describe(
      "Estimated monthly transaction volume, e.g. '$10k-$50k', '$1M+'."
    )
  },
  annotations: {
    readOnlyHint: false,
    idempotentHint: false,
    openWorldHint: true
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data: saved, error: saveError } = await supabase.from("user_demo_requests").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      email: input.email,
      company: input.company ?? null,
      message: input.message,
      monthly_volume: input.monthly_volume ?? null,
      status: "pending"
    }).select().single();
    if (saveError) {
      return {
        content: [
          { type: "text", text: `Could not save request: ${saveError.message}` }
        ],
        isError: true
      };
    }
    try {
      const url = `${process.env.SUPABASE_URL}/functions/v1/send-contact-email`;
      const res = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
          Authorization: `Bearer ${ctx.getToken()}`
        },
        body: JSON.stringify({
          name: input.name,
          email: input.email,
          company: input.company ?? "",
          message: input.message,
          monthly_volume: input.monthly_volume ?? "",
          source: "mcp",
          user_id: ctx.getUserId()
        })
      });
      if (!res.ok) {
        const text = await res.text();
        console.warn(`Email send failed [${res.status}]: ${text}`);
      }
    } catch (e) {
      console.warn("Email send exception", e);
    }
    return {
      content: [
        {
          type: "text",
          text: `Demo request submitted (id ${saved.id}). Sales will be in touch at ${input.email}.`
        }
      ],
      structuredContent: { request: saved }
    };
  }
});

// src/lib/mcp/tools/list-demo-requests.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_demo_requests_default = defineTool2({
  name: "list_demo_requests",
  title: "List my demo requests",
  description: "List the signed-in user's own demo / contact requests, most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("user_demo_requests").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { requests: data }
    };
  }
});

// src/lib/mcp/tools/update-demo-request.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var update_demo_request_default = defineTool3({
  name: "update_demo_request",
  title: "Update a demo request",
  description: "Update fields of one of the signed-in user's own demo requests. Only the fields provided are updated.",
  inputSchema: {
    id: z3.string().uuid().describe("ID of the demo request to update."),
    name: z3.string().min(1).optional(),
    email: z3.string().email().optional(),
    company: z3.string().optional(),
    message: z3.string().min(1).optional(),
    monthly_volume: z3.string().optional(),
    status: z3.string().optional()
  },
  annotations: {
    readOnlyHint: false,
    idempotentHint: true,
    destructiveHint: false,
    openWorldHint: false
  },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const clean = Object.fromEntries(
      Object.entries(patch).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(clean).length === 0) {
      return { content: [{ type: "text", text: "No fields to update." }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("user_demo_requests").update(clean).eq("id", id).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Updated request ${data.id}.` }],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/delete-demo-request.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var delete_demo_request_default = defineTool4({
  name: "delete_demo_request",
  title: "Delete a demo request",
  description: "Delete one of the signed-in user's own demo requests. This cannot be undone.",
  inputSchema: {
    id: z4.string().uuid().describe("ID of the demo request to delete.")
  },
  annotations: {
    readOnlyHint: false,
    idempotentHint: true,
    destructiveHint: true,
    openWorldHint: false
  },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser4(ctx).from("user_demo_requests").delete().eq("id", id);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: `Deleted request ${id}.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nzquideigitrirpmvjqw";
var mcp_default = defineMcp({
  name: "kredibilitypay-mcp",
  title: "KredibilityPay",
  version: "0.1.0",
  instructions: "Tools for KredibilityPay. Submit demo/contact requests to sales on behalf of the signed-in user, and read/update/delete that user's own submitted requests.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    submit_demo_request_default,
    list_demo_requests_default,
    update_demo_request_default,
    delete_demo_request_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
